### ISSUE TITLE
https://trisotech.github.io/js/oagis-bpmn-validator.js gets loaded, but fails in a 404

### ISSUE THREAD

**Issue by lukas-mertens** [Trisotech/OAGIS-BPMN-2.0-Validator#1]
Currently the validator doesn't work for me. It seems to be the case because it tries to load https://trisotech.github.io/js/oagis-bpmn-validator.js but fails to do so:

![image](https://user-images.githubusercontent.com/10901304/145591250-b96d62e2-80e2-4800-ad5d-77fdba764ecb.png)

This leads to an error here: 
![image](https://user-images.githubusercontent.com/10901304/145591351-a7d2808d-7a78-4ecb-b92e-fa5c4157466e.png)
when you choose a file

**Comment by SimonRinguette** [comment]
Hi Lukas,

This is a 9 year old project that did not receive a lot of love through the years. You can find the JS file the source, it seems that github has changed their hosting URL since then. 

Feel free to submit a PR with a fix.

**Comment by lukas-mertens** [comment]
@SimonRinguette Thanks for merging. I think you now have to merge to the gh-pages branch to deploy the change
